name: Format Terraform Cloud Variables
on:
  workflow_call:
    inputs:
      variables:
        required: false
        type: string
        description: Variables to append to the remote variables list
    secrets:
      TF_TOKEN:
        required: true
        description: A Terraform Cloud token
    outputs:
      variables:
        description: The formatted variables as a JSON list
        value: ${{ jobs.format-variables.outputs.variables }}
jobs:
  format-variables:
    runs-on: ubuntu-latest
    outputs:
      variables: ${{ toJson(fromJson(steps.provider.outputs.output).variables.Value) }}
    steps:
      - name: Fetch Workspace Variables
        uses: ryanwholey/terraform-cloud-remote-state-action@main
        id: provider
        with:
          workspace: terraform-credential-provider
          organization: ryanwholey
          address: https://app.terraform.io
          token: ${{ secrets.TF_TOKEN }}
