name: Update Semver
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - '**'
permissions:
  contents: read
jobs:
  update-semver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-update-semver@v1
